<input type="hidden" name="id" <?php $validator->show_id(); ?>>

<?php
if (!empty($validator->show_error_company_id()) || !empty($validator->show_error_id())) {
    ?>
    <div class="form-group">
        <?php $validator->show_error_company_id(); ?>
        <?php $validator->show_error_id(); ?>
    </div>
    <?php
}
?>

<div class="form-group">
    <label for="inputName">Nombre<span class="align-middle" style="color: red; font-size: 0.5rem;"><i class="fas fa-asterisk"></i></span></label>
    <input type="text" class="form-control" id="inputName" name="name" maxlength="50" style="text-transform: uppercase;" placeholder="" <?php $validator->show_name(); ?> required autofocus>
    <?php $validator->show_error_name(); ?>
</div>

<div class="form-group">
    <label for="inputSymbol">S&#237;mbolo<span class="align-middle" style="color: red; font-size: 0.5rem;"><i class="fas fa-asterisk"></i></span></label>
    <input type="text" class="form-control" id="inputSymbol" name="symbol" maxlength="5" style="text-transform: uppercase;" placeholder="" <?php $validator->show_symbol(); ?> required>
    <?php $validator->show_error_symbol(); ?>
</div>

<div class="form-check mb-1">
    <input type="checkbox" class="form-check-input" id="checkDivisible" name="divisible" <?php $validator->show_divisible(); ?>>
    <label class="form-check-label" for="checkDivisible">Divisible</label>
</div>

<div class="form-group">
    <?php $validator->show_error_divisible(); ?>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="checkActive" name="active" <?php $validator->show_active(); ?>>
    <label class="form-check-label" for="checkActive">Vigente</label>
</div>

<div class="form-group">
    <?php $validator->show_error_active(); ?>
</div>