<?php
if (($request == 'new' || $request == 'edit') && isset($validator)) {    // new or edit.
    include_once 'validated.inc.phtml';
} elseif ($request == 'new' && !isset($model) && !isset($validator)) {    // new.
    include_once 'new.inc.phtml';
} elseif ($request == 'edit' && isset($model) && !isset($validator)) {    // edit.
    include_once 'edit.inc.phtml';
} elseif (($request == 'view' || $request == 'delete') && isset($model) && !isset($validator)) {    // view or delete.
    include_once 'delete.inc.phtml';
}
?>