<input type="hidden" name="id" value="<?php echo $model->get_id(); ?>">

<div class="form-group row">
    <label for="inputName" class="col-3 col-form-label">Nombre<span class="align-middle" style="color: red; font-size: 0.5rem;"><i class="fas fa-asterisk"></i></span></label>
    <div class="col-9">
        <input type="text" class="form-control" id="inputName" name="name" maxlength="50" style="text-transform: uppercase;" placeholder="" value="<?php echo $model->get_name(); ?>" required autofocus>
    </div>
</div>

<div class="form-group row">
    <label for="inputPercentage1" class="col-3 col-form-label">&#37; 1</label>
    <div class="col-9">
        <input type="number" class="form-control" id="inputPercentage1" name="p1" min="0" max="999" step="0.01" placeholder="" value="<?php echo $model->get_p1(); ?>">
    </div>
</div>

<div class="form-group row">
    <label for="inputPercentage2" class="col-3 col-form-label">&#37; 2</label>
    <div class="col-9">
        <input type="number" class="form-control" id="inputPercentage2" name="p2" min="0" max="999" step="0.01" placeholder="" value="<?php echo $model->get_p2(); ?>">
    </div>
</div>

<div class="form-group row">
    <label for="inputPercentage3" class="col-3 col-form-label">&#37; 3</label>
    <div class="col-9">
        <input type="number" class="form-control" id="inputPercentage3" name="p3" min="0" max="999" step="0.01" placeholder="" value="<?php echo $model->get_p3(); ?>">
    </div>
</div>

<div class="form-group row">
    <label for="inputPercentage4" class="col-3 col-form-label">&#37; 4</label>
    <div class="col-9">
        <input type="number" class="form-control" id="inputPercentage4" name="p4" min="0" max="999" step="0.01" placeholder="" value="<?php echo $model->get_p4(); ?>">
    </div>
</div>

<div class="form-group row">
    <label for="inputPercentage5" class="col-3 col-form-label">&#37; 5</label>
    <div class="col-9">
        <input type="number" class="form-control" id="inputPercentage5" name="p5" min="0" max="999" step="0.01" placeholder="" value="<?php echo $model->get_p5(); ?>">
    </div>
</div>

<div class="form-group row">
    <div class="col-3"></div>
    <div class="col-9">
        <div class="form-check">
            <input type="checkbox" class="form-check-input" id="checkActive" name="active" <?php if ($model->is_active()) echo 'checked'; ?>>
            <label class="form-check-label" for="checkActive">Vigente</label>
        </div>
    </div>
</div>