<div class="container pt-5">
    <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6 card p-0">
            <div class="card-header">
                <h4><b>Crea una cuenta</b></h4>
            </div>
            <div class="card-body">
                <form class="form" role="form" autocomplete="off" method="post" enctype="application/x-www-form-urlencoded" action="<?php echo ROUTE_SIGNUP; ?>">
                    <?php
                    if (isset($_POST['submit'])) {
                        include_once 'validated.inc.phtml';
                    } else {
                        include_once 'new.inc.phtml';
                    }
                    ?>
                </form>
                <div class="row mt-3">
                    <div class="col-md-12 text-center">
                        <span>¿Ya tienes cuenta?</span>
                        <a href="<?php echo ROUTE_SIGNIN; ?>">Inicia sesi&#243;n</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12 text-center">
            <p class="mt-3 text-muted">&copy; 2000-2018, Turtle Software Paraguay</p>
        </div>
    </div>
</div>