<div class="container">
    <div class="row mt-3">
        <div class="col-md-12 text-center">
            <img src="<?php echo ROUTE_IMG ?>spirit-animal-logo.png" alt="spirit animal logo" width="100" height="100">
        </div>
    </div>
    <div class="row pl-5 pr-5">
        <div class="col-md-3">
        </div>
        <div class="col-md-6 card p-0">
            <div class="card-header">
                <h4><b>Sistema de Gesti&#243;n Pytyv&#245;</b></h4>
            </div>
            <div class="card-body">
                <form class="form" role="form" autocomplete="off" method="post" enctype="application/x-www-form-urlencoded" action="<?php echo ROUTE_SIGNIN; ?>">
                    <input type="hidden" name="authenticity_token" value="<?php echo bin2hex(random_bytes(32)); ?>">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="inputUserName" class="label">Nombre de usuario</label>
                                <input type="text" maxlength="25" name="username" id="inputUserName" class="form-control" placeholder="" required autofocus>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-12">
                                <label for="inputPassword" class="label">Contrase&#241;a</label>
                                <input type="password" maxlength="25" name="password" id="inputPassword" class="form-control" placeholder="" required>
                            </div>
                        </div>
                    </div>

                    <?php
                    if (isset($_POST['signin'])) {
                        $validator->show_error();
                    }
                    ?>

                    <button type="submit" class="btn btn-success btn-lg btn-block" name="signin">Ingresar</button>
                </form>
                <div class="row mt-3">
                    <div class="col-md-7 text-left">
                        <a href="<?php echo '#'; ?>">¿Olvidaste tu contrase&#241;a?</a>
                    </div>
                    <div class="col-md-5 text-right">
                        <a href="<?php echo ROUTE_SIGNUP; ?>">Crea una cuenta</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-12 text-center">
            <p class="mt-3 text-muted">&copy; 2000-2018, Turtle Software Paraguay</p>
        </div>
    </div>
</div>