<input type="hidden" name="id" value="<?php echo $model->get_id(); ?>">

<div class="form-group">
    <label for="selectDepar">Departamento<span class="align-middle" style="color: red; font-size: 0.5rem;"><i class="fas fa-asterisk"></i></span></label>
    <select class="form-control" id="selectDepar" name="depar_id" disabled readonly>
        <?php
        foreach ($depars as $depar) {
            ?>
            <option value="<?php echo $depar->get_id(); ?>"<?php if ($depar->get_id() == $model->get_depar_id()) echo ' selected';?>><?php echo $depar->get_name(); ?></option>
            <?php
        }
        ?>
    </select>
</div>

<div class="form-group">
    <label for="selectCity">Ciudad<span class="align-middle" style="color: red; font-size: 0.5rem;"><i class="fas fa-asterisk"></i></span></label>
    <select class="form-control" id="selectCity" name="city_id" disabled readonly>
        <?php
        foreach ($cities as $city) {
            ?>
            <option value="<?php echo $city->get_id(); ?>"<?php if ($city->get_id() == $model->get_city_id()) echo ' selected';?>><?php echo $city->get_name(); ?></option>
            <?php
        }
        ?>
    </select>
</div>

<div class="form-group">
    <label for="inputName">Nombre<span class="align-middle" style="color: red; font-size: 0.5rem;"><i class="fas fa-asterisk"></i></span></label>
    <input type="text" class="form-control" id="inputName" name="name" maxlength="50" style="text-transform: uppercase;" placeholder="" value="<?php echo $model->get_name(); ?>" readonly>
</div>

<div class="form-check mb-3">
    <input type="checkbox" class="form-check-input" id="checkActive" name="active" <?php if ($model->is_active()) echo 'checked'; ?> onclick="return false;" disabled readonly>
    <label class="form-check-label" for="checkActive">Vigente</label>
</div>